### ISSUE TITLE
Snapshot doesn't allow you to edit posts due to a fatal error

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/snapshot#1]
Awkwardly, anyone who isn't using SiteOrigin Premium or Snapshot plus is unable to use Snapshot effectively at the moment due to a fatal error caused by the lack of SiteOrigin Premium. This is due to the usage of the [siteorigin_premium_call_function() function](https://github.com/siteorigin/snapshot/blame/develop/inc/admin.php#L78) and the lack of checking if the function exists (which obviously won't).

**Comment by gregpriday** [comment]
Nicely spotted!
